"""
Whale-VAD Reproduction - Configuration Module
=============================================

Centralized configuration for all hyperparameters, paths, and constants used
across the Whale-VAD reproduction pipeline. All values are chosen to match the
paper (Geldenhuys et al., DCASE 2025) and the authors' public reference
implementation at https://github.com/CMGeldenhuys/Whale-VAD, unless otherwise
indicated in a comment.

This module is imported as ``cfg`` throughout the codebase; modifying a value
here propagates to every downstream component (data loading, model, training,
post-processing, inference).

Paper sections referenced in comments:
    - 5.1  Preprocessing (segmentation and windowing)
    - 5.2  Feature extractor (STFT, phase features, mean subtraction)
    - 5.3  Regularization (dropout)
    - 5.4  Whale-VAD model architecture
    - 5.5  Stochastic negative undersampling
    - 5.6  Loss function and optimizer
    - 5.8  Postprocessing (smoothing, thresholding, merging)

Reference
---------
Geldenhuys, C. M., Tonitz, D., & Niesler, T. (2025).
Whale-VAD: Whale Vocalisation Activity Detection.
In Proceedings of the Detection and Classification of Acoustic Scenes and
Events Challenge (DCASE 2025).
"""

from pathlib import Path


# ======================================================================
# Filesystem paths
# ======================================================================
# These paths are machine-specific and must be edited for your environment.
# All other configuration values can typically be left at their defaults.

#: Root of the BioDCASE 2026 development dataset. Expected layout:
#:     DATA_ROOT/
#:       train/
#:         annotations/{dataset_name}.csv
#:         audio/{dataset_name}/*.wav
#:       validation/
#:         annotations/{dataset_name}.csv
#:         audio/{dataset_name}/*.wav
DATA_ROOT = Path("/home/matthias-nagl/BioDCASE/task/2026_BioDCASE_development_set/")

#: Directory under which all training runs write their checkpoints and logs.
#: Each run creates a timestamped subdirectory (e.g. ``runs/whalevad_20260419_085020/``).
OUTPUT_DIR = Path("./runs")

#: Default destination for the challenge submission CSV generated by ``inference.py``.
SUBMISSION_PATH = Path("./submission.csv")

#: Optional path to contrastive-pretrained encoder weights. If ``None``, the
#: supervised model is trained from scratch. Set via ``--pretrained`` flag on
#: ``train.py`` rather than by editing this value directly.
PRETRAINED_PATH = None

#: Directory containing unlabeled WAV files used for self-supervised
#: pretraining (see ``pretrain_contrastive.py``). Only relevant for the SSL
#: extension; unused by the core paper reproduction.
UNLABELED_DATA_DIR = Path("./data_unlabeled/combined")


# ======================================================================
# Dataset splits
# ======================================================================
# Partitioning follows Table 1 of the paper. The eight training sites and
# three validation sites are fixed; the two evaluation sites (Kerguelen2020,
# DDU2021) are the unlabeled test sets used for challenge submission.

#: Training sites (labels available).
TRAIN_DATASETS = [
    "ballenyislands2015",
    "casey2014",
    "elephantisland2013",
    "elephantisland2014",
    "greenwich2015",
    "kerguelen2005",
    "maudrise2014",
    "rosssea2014",
]

#: Validation sites (labels available, used for hyperparameter tuning and
#: model selection).
VAL_DATASETS = [
    "casey2017",
    "kerguelen2014",
    "kerguelen2015",
]

#: Evaluation sites (labels withheld; used only for challenge submission).
EVAL_DATASETS = [
    "kerguelen2020",
    "ddu2021",
]


# ======================================================================
# Audio and spectrogram parameters (Section 5.2)
# ======================================================================

#: Audio sample rate in Hz. All hydrophone recordings in the ATBFL corpus
#: are resampled to 250 Hz by the dataset provider.
SAMPLE_RATE = 250

#: Temporal stride between consecutive output frames (seconds). The model
#: produces one prediction every 20 ms, matching the paper's classification
#: resolution.
FRAME_STRIDE_S = 0.02

#: STFT window size in samples. At 250 Hz this gives a ~1-second analysis
#: window, which is appropriate for low-frequency whale vocalizations whose
#: fundamental periods are on the order of 1-10 seconds.
N_FFT = 256
WIN_LENGTH = 256

#: STFT hop length in samples. ``HOP_LENGTH = SAMPLE_RATE * FRAME_STRIDE_S``
#: (i.e. 5 samples at 250 Hz = 20 ms) to match the target frame rate.
HOP_LENGTH = 5

#: Per-frequency mean subtraction mode. "demean" subtracts, for each
#: frequency bin independently, the temporal mean of the magnitude spectrum
#: computed over the whole segment. This removes stationary channel noise
#: without affecting transient events. See Section 5.2 of the paper.
NORM_FEATURES = "demean"

#: Complex-value representation for STFT output. "trig" stacks
#: ``[magnitude, cos(phase), sin(phase)]`` as three input channels, which is
#: empirically more learnable than raw real/imaginary parts. See Section 5.4.
COMPLEX_REPR = "trig"


# ======================================================================
# Classes and label collapsing (Section 4)
# ======================================================================
# The ATBFL corpus provides seven fine-grained call-type labels, but the
# DCASE 2025 challenge evaluates on three coarse classes. The ablation in
# Table 3 of the paper shows the coarse grouping yields +15.2% F1 over the
# 7-class setup by reducing annotation inconsistency between sites.

#: Fine-grained call type labels as they appear in the raw annotation CSVs.
CALL_TYPES_7 = ["bma", "bmb", "bmz", "bmd", "bpd", "bp20", "bp20plus"]

#: Coarse evaluation labels used by the challenge.
#:   - ``bmabz``: Antarctic blue whale Z-call and its syllabic components
#:   - ``d``:     D-call (blue whale downsweep)
#:   - ``bp``:    fin whale pulse calls (includes all three fin subtypes)
CALL_TYPES_3 = ["bmabz", "d", "bp"]

#: Maps fine-grained to coarse labels.
COLLAPSE_MAP = {
    "bma": "bmabz", "bmb": "bmabz", "bmz": "bmabz",
    "bmd": "d",  "bpd": "d",
    "bp20": "bp", "bp20plus": "bp",               
}

#: If True, train and evaluate on the 3-class task. If False, the model
#: outputs 7 fine-grained call-type logits which can be collapsed at
#: evaluation time via COLLAPSE_MAP.
#:
#: NOTE: The official Geldenhuys checkpoint (WhaleVAD_ATBFL_3P-c6f6a07a.pt)
#: outputs 7 classes despite the "3P" in its filename — the "3-class problem"
#: in the DCASE Table 2 ablation refers to *evaluating* in the 3-class space,
#: not to training a 3-class head. To match the official checkpoint exactly,
#: set this to False and use post-hoc collapse during evaluation.
USE_3CLASS = False


# ======================================================================
# Segmentation (Section 5.1)
# ======================================================================

#: Minimum duration (seconds) of the random silence padding prepended and
#: appended to each training call. The "collar" ensures the model learns to
#: localize calls rather than triggering on trivial segment-level cues.
COLLAR_MIN_S = 1.0

#: Maximum collar duration in seconds.
COLLAR_MAX_S = 5.0

#: Validation/evaluation segment length in seconds. Fixed windows produce
#: deterministic evaluation, unlike the variable-length training segments.
EVAL_SEGMENT_S = 30.0

#: Overlap between consecutive validation windows in seconds. Overlapping
#: windows are averaged during stitching to smooth predictions at segment
#: boundaries.
EVAL_OVERLAP_S = 2.0

#: Minimum call duration (seconds). Annotations shorter than this are
#: filtered out during segment construction. Paper uses 500 ms.
MIN_CALL_DURATION_S = 0.5

#: Maximum call duration (seconds). Annotations longer than this are filtered
#: out; such entries are almost always annotation errors or multi-call
#: groupings.
MAX_CALL_DURATION_S = 30.0


# ======================================================================
# Negative undersampling (Section 5.5)
# ======================================================================

#: Ratio of negative-only segments to positive segments per epoch. The paper
#: uses approximately 1:1 balance via stochastic undersampling: each epoch
#: samples a fresh random subset of negative segments so that over many
#: epochs the model sees the full negative distribution.
NEG_RATIO = 1.0


# ======================================================================
# Model architecture (Section 5.4, Table 2)
# ======================================================================

#: Number of filters in the learnable filterbank (first convolutional layer).
FILTERBANK_OUT_CH = 64

#: Number of channels in the main feature extractor.
FEAT_EXTRACTOR_CH = 128

#: Bottleneck channel count inside the residual block.
BOTTLENECK_CH = 64

#: Dimension of the per-frame feature vector fed into the BiLSTM.
PROJECTION_DIM = 64

#: Hidden size of each BiLSTM direction (total output dim is ``2 * LSTM_HIDDEN``).
LSTM_HIDDEN = 128

#: Number of stacked BiLSTM layers.
LSTM_LAYERS = 2

#: Dropout applied between BiLSTM layers. Paper reports sweeping 20-50% and
#: finding 50% optimal for their setup.
LSTM_DROPOUT = 0.5

#: Dropout probability inside the residual bottleneck.
BOTTLENECK_DROPOUT = 0.1

#: Spatial dropout (Dropout2d) applied at the entry to the depthwise
#: aggregation block.
AGG_DROPOUT = 0.2


# ======================================================================
# Training hyperparameters (Section 5.6)
# ======================================================================

#: Maximum number of training epochs. The DCASE 2025 tech report does not
#: specify a fixed epoch count; training is stopped via best-val-loss model
#: selection. We use a generous cap and rely on early stopping in train.py.
EPOCHS = 150

#: Mini-batch size (segments per gradient step). The DCASE tech report does
#: not specify a batch size; 32 is a safe default that fits comfortably on
#: a single GPU at this model scale.
BATCH_SIZE = 32

#: Learning rate for AdamW.
#:
#: The DCASE 2025 tech report Section 2.6 specifies LR=1e-5. In our
#: reproduction at LR=1e-5 we observed that the classifier weights
#: barely moved across 21 epochs (verified by inspecting classifier.bias
#: which stayed at -2.995 vs an init of -3.000). Per-step gradient
#: magnitudes for the rare-class biases are on the order of 3e-5, so at
#: LR=1e-5 the per-step update is 3e-10 — too small to learn within a
#: practical epoch budget. We therefore deviate to 1e-4 (10x the paper)
#: which produces visible weight movement.
#:
#: The paper's smaller LR may have been viable for them due to:
#:   - Much longer training horizons (paper does not specify epoch count)
#:   - The bounding-box auxiliary loss providing additional gradient signal
#:   - Pack-padded LSTM excluding padded frames (different gradient flow)
#: We don't have those, so a higher LR is the practical compromise.
LR = 1e-4

#: AdamW weight decay. DCASE tech report value (0.001).
WEIGHT_DECAY = 0.001

#: AdamW first moment decay (β1).
BETA1 = 0.9

#: AdamW second moment decay (β2).
BETA2 = 0.999

#: Maximum L2 norm for gradient clipping. Prevents occasional gradient spikes
#: from destabilizing the BiLSTM.
GRAD_CLIP = 1.0


# ======================================================================
# Loss function (Section 5.6)
# ======================================================================

#: If True, apply per-class positive weights in the BCE loss. Weights are
#: computed as ``w_c = N / P_c`` where ``N`` is the number of negative
#: segments and ``P_c`` is the number of positive segments for class c; see
#: ``model.compute_class_weights``. The DCASE tech report Section 2.6 uses
#: weighted BCE.
USE_WEIGHTED_BCE = True

#: If True, apply focal modulation on top of the BCE loss. The DCASE tech
#: report Table 2 shows that adding focal loss on top of weighted BCE gave
#: a +8.0% F1 improvement, taking the model from 0.375 to 0.405 (before the
#: 3-class evaluation step that finally got to 0.440). So both are enabled
#: together to match the DCASE recipe.
USE_FOCAL_LOSS = False

#: Class-imbalance parameter for focal loss. DCASE tech report Section 2.6:
#: "we set the class imbalance term to 0.25 and focus term to 2, following
#: the recommendations in the original paper [Lin et al. 2018]."
FOCAL_ALPHA = 0.25

#: Focusing parameter for focal loss. Same source as FOCAL_ALPHA above.
FOCAL_GAMMA = 2.0


# ======================================================================
# Postprocessing (Section 5.8)
# ======================================================================

#: Width of the median filter applied to per-frame probabilities before
#: thresholding, in milliseconds. Smooths out short spurious spikes.
SMOOTH_KERNEL_MS = 500

#: Maximum gap (seconds) between two detections of the same class on the same
#: file that should still be merged into a single event.
MERGE_GAP_S = 0.5

#: Minimum duration (seconds) for a post-merge detection to be kept.
POST_MIN_DUR_S = 0.5

#: Maximum duration (seconds) for a post-merge detection to be kept.
POST_MAX_DUR_S = 30.0

#: Default per-class confidence thresholds, applied when no tuned thresholds
#: have been supplied. Call ``tune_thresholds.py`` after training to produce
#: class-specific values that usually outperform the naive 0.5.
DEFAULT_THRESHOLDS = [0.5, 0.5, 0.5]


# ======================================================================
# Runtime
# ======================================================================

#: Number of parallel worker processes for PyTorch DataLoaders.
NUM_WORKERS = 16

#: Random seed, applied to ``random``, ``numpy``, and ``torch`` at the start
#: of every entry point for reproducibility.
SEED = 42


# ======================================================================
# Convenience helpers
# ======================================================================
# These small functions centralize logic that depends on the 3-class toggle,
# so that every call site does not have to repeat the conditional.

def n_classes() -> int:
    """Return the number of output classes the model should produce."""
    return 3 if USE_3CLASS else 7


def class_names() -> list[str]:
    """Return the ordered list of class label strings currently in use."""
    return list(CALL_TYPES_3) if USE_3CLASS else list(CALL_TYPES_7)


def class_to_idx() -> dict[str, int]:
    """Return a mapping from class name to zero-based output index."""
    return {c: i for i, c in enumerate(class_names())}
